### PR TITLE
Fix#21 step2 to api2.1.1

### PR DESCRIPTION
**Pull request by keighrim**
resolving #21

### CODE REVIEW

**Comment by chunqishi** [comment]
Hi, Keigh,

You created v2.1.1.

Which version of code should we work on? 2.1.1?

Best regards,

Chunqi

## 

Chunqi

**Comment by chunqishi** [comment]
Hi, Keigh,

You deleted v2.1.1 of edu.brandeis.cs.opennlp-web-service???

Why delete it?

Best.

## 

Chunqi

**Comment by chunqishi** [comment]
Again,  which branch should we work on?

## 

Chunqi

**Comment by chunqishi** [comment]
Hi, Keigh,

I totally confused about current version situation.

Should I work on v2.0.1 or should I work on v2.1.1.

If v2.0.1,  what feature in v2.1.1 (stanford) that will be only used for
next version ?

if v2.1.1, why no v2.1.1 (opennlp) available.

Best,

## 

Chunqi

**Comment by keighrim** [comment]
I create stanfordnlp wrapper to 2.1.1 to match the version of
org.lappsgrid.all,
But as you said, 2.0.1-snapshot is what's on the docker image, so I think
we should work on 2.0.1 branch of stanford.

While the opennlp, I didn't updated to 2.1.1 at the firstplace. We made a
little fix on it on Saturday, and that was 2.0.1.

But let's work on 2.0.1 for both for the demo.

Best,
Keigh.

**Comment by chunqishi** [comment]
I got it.

If the lapps.api is not stable,  Keith will upgrade it.
Maybe we do not need to create a new branch for that, as we will update to
new api soon until everything is stable.

Anyway,  let us work together on v2.0.1 :-  )

Best,

## 

Chunqi

**Pull request merged**
